/**
 * utils/unifiedBridge.ts
 *
 * This module acts as a bridge between the Omni-MDX native AST (generated by Rust)
 * and the `unified` ecosystem's HAST (HTML Abstract Syntax Tree).
 * It enables developers to use existing `rehype` plugins (like syntax highlighting)
 * seamlessly with the Omni-MDX engine.
 */

import { unified } from 'unified';
import type { PluggableList } from 'unified';
import type { Element, Text, Root, Node as HastNode } from 'hast';
import type { AstNode, AttrValueKind } from '../types/MdxAST';

/**
 * Converts an Omni-MDX `AstNode` into a `unified` ecosystem `HastNode`.
 * This allows standard `rehype` plugins to understand and traverse the AST.
 *
 * @param node - The internal AST node generated by the Rust parser.
 * @returns The equivalent `hast` node.
 */
function toHast(node: AstNode): HastNode {
  if (node.node_type === 'text') {
    return { type: 'text', value: node.content ?? '' } as Text;
  }

  if (node.node_type === 'fragment') {
    return {
      type: 'root',
      children: (node.children || []).map(toHast) as any[]
    } as Root;
  }

  const properties: Record<string, any> = {};
  let classNameArray: string[] | undefined = undefined;

  properties['dataOmniTag'] = node.node_type;
  if (node.self_closing) {
     properties['dataOmniSelfClosing'] = true;
  }

  if (node.attributes) {
    const attrs = typeof node.attributes === 'string' 
      ? JSON.parse(node.attributes) 
      : node.attributes;
    
    for (const [key, val] of Object.entries(attrs)) {
      const v = val as AttrValueKind;
      if (v.kind === 'text') {
        if (key === 'className' || key === 'class') {
          classNameArray = v.value.split(' ');
          properties['className'] = classNameArray;
        } else {
          properties[key] = v.value;
        }
      }
      if (v.kind === 'boolean') properties[key] = true;
      if (v.kind === 'expression') properties[key] = v.value; 
      if (v.kind === 'ast') properties[key] = JSON.stringify({ _omni_ast: v.value });
    }
  }

  if (node.node_type === 'pre') {
    const hasCodeChild = node.children?.some(c => c.node_type === 'code');
    if (!hasCodeChild) {
      const codeProps: Record<string, any> = {};
      if (classNameArray) codeProps['className'] = classNameArray;

      return {
        type: 'element',
        tagName: 'pre',
        properties: {},
        children: [
          {
            type: 'element',
            tagName: 'code',
            properties: codeProps,
            children: (node.children || []).map(toHast) as any[]
          }
        ]
      } as Element;
    }
  }

  return {
    type: 'element',
    tagName: node.node_type.toLowerCase(),
    properties,
    children: (node.children || []).map(toHast) as any[]
  } as Element;
}

/**
 * Converts a `unified` ecosystem `HastNode` back into an Omni-MDX `AstNode`.
 * This is called after the plugins have finished modifying the tree.
 *
 * @param node - The processed `hast` node.
 * @returns The corresponding internal `AstNode` ready for React rendering.
 */
function fromHast(node: HastNode): AstNode {
  if (node.type === 'text') {
    return { node_type: 'text', content: (node as Text).value };
  }

  if (node.type === 'root') {
    return {
      node_type: 'fragment',
      children: ((node as Root).children || []).map(fromHast)
    };
  }

  const el = node as Element;
  const attributes: Record<string, AttrValueKind> = {};
  
  let originalTag = el.tagName || 'div';
  let selfClosing = false;
  
  if (el.properties) {
    for (const [key, val] of Object.entries(el.properties)) {
        if (key === 'dataOmniTag') {
            originalTag = String(val);
            continue;
        }
        if (key === 'dataOmniSelfClosing') {
            selfClosing = true;
            continue;
        }

        if (key === 'className' && Array.isArray(val)) {
            attributes['className'] = { kind: 'text', value: val.join(' ') };
        } else if (typeof val === 'boolean') {
            attributes[key] = { kind: 'boolean' };
        } else if (typeof val === 'string' && val.startsWith('{"_omni_ast":')) {
            try {
                const parsed = JSON.parse(val);
                attributes[key] = { kind: 'ast', value: parsed._omni_ast };
            } catch {
                attributes[key] = { kind: 'text', value: val };
            }
        } else if (val !== undefined && val !== null) {
            attributes[key] = { kind: 'text', value: String(val) };
        }
    }
  }

  return {
    node_type: originalTag,
    attributes,
    children: (el.children || []).map(fromHast),
    self_closing: selfClosing
  };
}

/**
 * Asynchronously executes an array of `unified` (rehype) plugins against the provided AST.
 * It translates the AST back and forth automatically.
 *
 * @param ast - The initial AST generated by the Omni-MDX Rust core.
 * @param plugins - An array of `unified` plugins to apply.
 * @returns A promise that resolves to the modified AST.
 */
export async function runUnifiedPipeline(
  ast: AstNode[], 
  plugins: PluggableList
): Promise<AstNode[]> {
  if (!plugins || plugins.length === 0) return ast;

  const rootNode: AstNode = { node_type: 'fragment', children: ast };
  
  const hastTree = toHast(rootNode);

  const processor = unified().use({ plugins });

  const processedHast = await processor.run(hastTree);
  const processedOmniAst = fromHast(processedHast);
  
  return processedOmniAst.children || [];
}

/**
 * Synchronously executes an array of `unified` (rehype) plugins against the provided AST.
 * 
 * ⚠️ **Warning:** All provided plugins must be strictly synchronous. If a plugin relies on
 * async operations (like network requests or async file reading), this will throw an error.
 *
 * @param ast - The initial AST generated by the Omni-MDX Rust core.
 * @param plugins - An array of synchronous `unified` plugins to apply.
 * @returns The modified AST.
 */
export function runUnifiedPipelineSync(
  ast: AstNode[], 
  plugins: PluggableList
): AstNode[] {
  if (!plugins || plugins.length === 0) return ast;

  const rootNode: AstNode = { node_type: 'fragment', children: ast };
  const hastTree = toHast(rootNode);

  const processor = unified().use({ plugins });

  const processedHast = processor.runSync(hastTree);

  const processedOmniAst = fromHast(processedHast);
  return processedOmniAst.children || [];
}