use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::collections::HashMap;

/// Represents all possible errors that can occur during MDX parsing or AST serialization.
#[derive(Debug)]
pub enum ParseError {
    /// The input byte slice is not valid UTF-8.
    InvalidUtf8,
    /// A JSX block was opened but never closed. Contains the byte offset where it started.
    UnclosedJsxBlock { pos: usize },
    /// A specific JSX tag was opened but its corresponding closing tag was not found.
    UnclosedTag { name: String },
    /// An unexpected character was encountered during parsing.
    UnexpectedToken { pos: usize, got: char },
    /// An error occurred while serializing the AST to JSON.
    Serialization(serde_json::Error),
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ParseError::InvalidUtf8 => write!(f, "Invalid UTF-8 input"),
            ParseError::UnclosedJsxBlock { pos } => {
                write!(f, "Unclosed JSX block starting at byte {pos}")
            }
            ParseError::UnclosedTag { name } => write!(f, "Unclosed JSX tag <{name}>"),
            ParseError::UnexpectedToken { pos, got } => {
                write!(f, "Unexpected token '{got}' at byte {pos}")
            }
            ParseError::Serialization(e) => write!(f, "Serialization error: {e}"),
        }
    }
}

impl std::error::Error for ParseError {}

impl From<serde_json::Error> for ParseError {
    fn from(e: serde_json::Error) -> Self {
        ParseError::Serialization(e)
    }
}

/// Represents the evaluated value of a JSX or HTML attribute.
///
/// This enum captures the different syntactical forms an attribute can take in MDX,
/// ensuring that expressions and sub-trees are preserved for the frontend renderer.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "kind", content = "value", rename_all = "lowercase")]
pub enum AttrValue<'a> {
    /// A standard string literal value (e.g., `prop="hello"` or `prop='hi'`).
    Text(Cow<'a, str>),
    /// A JavaScript/JSX expression enclosed in braces (e.g., `prop={someExpr}`).
    /// The expression is stored as a raw string without the surrounding braces.
    Expression(Cow<'a, str>),
    /// A boolean attribute without an explicit value (e.g., `<Component disabled />`).
    /// Implicitly resolves to `true` in React.
    Boolean,
    /// An attribute whose value contains a nested MDX AST (e.g., render props or rich text).
    Ast(Vec<AstNode<'a>>),
}

/// A single node within the Abstract Syntax Tree (AST) generated by the MDX parser.
///
/// This structure is designed to be easily serialized to JSON and consumed by
/// a frontend framework (like React) to render the final component tree.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct AstNode<'a> {
    /// The tag name or element type (e.g., `"p"`, `"h1"`, `"text"`, `"SplitLayout"`).
    pub node_type: Cow<'a, str>,

    /// The raw text content. This is only populated for leaf nodes of type `"text"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<Cow<'a, str>>,

    /// A map of JSX or HTML attributes assigned to this node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<HashMap<Cow<'a, str>, AttrValue<'a>>>,

    /// The nested child nodes contained within this element.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub children: Vec<AstNode<'a>>,

    /// Indicates whether the tag was self-closing in the source MDX (e.g., `<Chart />`).
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub self_closing: bool,
}

impl<'a> AstNode<'a> {
    /// Creates a new text leaf node with the specified content.
    pub fn text(content: impl Into<Cow<'a, str>>) -> Self {
        AstNode {
            node_type: "text".into(),
            content: Some(content.into()),
            attributes: None,
            children: vec![],
            self_closing: false,
        }
    }

    /// Creates a new structural element node without content or attributes.
    pub fn element(node_type: impl Into<Cow<'a, str>>, self_closing: bool) -> Self {
        AstNode {
            node_type: node_type.into(),
            content: None,
            attributes: None,
            children: vec![],
            self_closing,
        }
    }

    pub fn into_static(self) -> AstNode<'static> {
        AstNode {
            node_type: Cow::Owned(self.node_type.into_owned()),
            content: self.content.map(|c| Cow::Owned(c.into_owned())),
            attributes: self.attributes.map(|attrs| {
                attrs
                    .into_iter()
                    .map(|(k, v)| (Cow::Owned(k.into_owned()), v.into_static()))
                    .collect()
            }),
            children: self.children.into_iter().map(|c| c.into_static()).collect(),
            self_closing: self.self_closing,
        }
    }
}

impl<'a> AttrValue<'a> {
    pub fn into_static(self) -> AttrValue<'static> {
        match self {
            AttrValue::Text(s) => AttrValue::Text(Cow::Owned(s.into_owned())),
            AttrValue::Expression(s) => AttrValue::Expression(Cow::Owned(s.into_owned())),
            AttrValue::Boolean => AttrValue::Boolean,
            AttrValue::Ast(nodes) => {
                AttrValue::Ast(nodes.into_iter().map(|n| n.into_static()).collect())
            }
        }
    }
}
