"use client";

import React, { ReactNode, createContext, useContext } from "react";
import { useMdxConfig, MdxConfigProvider } from "./MDXConfigContext";
import type { MDXConfig } from "./types/MDXConfig";
import type { AttrValue, AstNode } from "./types/Ast";
import { MDXErrorBoundary } from "./MDXErrorBoundary";
import { InlineMath, BlockMath } from "react-katex";
import "katex/dist/katex.min.css";


/**
 * Tracks whether the renderer is currently inside a custom JSX component.
 * This prevents standard Markdown styles from bleeding into custom React components.
 */
const InsideJsxContext = createContext(false);

const MDXContent = ({ ast }: { ast: AstNode[] }) => {
  const { components } = useMdxConfig();
  const insideJsx = useContext(InsideJsxContext);

  /**
   * Transforms raw AST attribute values into native JavaScript/React values.
   * Moved INSIDE the component to safely access the recursive <MDXContent /> 
   * without relying on dangerous global variables.
   */
  const resolveAttr = (value: AttrValue): unknown => {
    switch (value.kind) {
      case "text": 
        return value.value;
      case "boolean": 
        return true;
      case "ast":
        // Render nested MDX sub-trees passed as props (e.g., `left={<Component />}`)
        return (
          <InsideJsxContext.Provider value={true}>
            <MDXContent ast={value.value} />
          </InsideJsxContext.Provider>
        );
      case "expression": {
        const expr = value.value.trim();
        // Dynamically evaluate JSON objects, arrays, or numbers.
        if (/^[\[{]/.test(expr) || /^-?\d/.test(expr)) {
          try { 
            return new Function(`"use strict"; return (${expr})`)(); 
          } catch { 
            return expr; 
          }
        }
        return expr;
      }
    }
  };

  /**
   * Recursively renders a single AST Node into a React Element.
   */
  const renderNode = (node: AstNode, index: number): ReactNode => {
    // Note: Using index as part of the key is acceptable here since the AST is static post-parsing.
    const key = `${node.node_type}-${index}`;

    // 1. Leaf Nodes (Text)
    if (node.node_type === "text") return node.content ?? null;

    // 2. Synthetic Fragments (Generated by Rust's paragraph un-wrapper)
    if (node.node_type === "fragment") {
      return <React.Fragment key={key}>{renderChildren(node)}</React.Fragment>;
    }

    // 3. LaTeX Math
    if (node.node_type === "InlineMath") {
      return <InlineMath key={key} math={node.content ?? ""} />;
    }
    if (node.node_type === "BlockMath") {
      return <BlockMath key={key} math={node.content ?? ""} />;
    }

    // 4. Resolve Node Attributes
    const nodeProps: Record<string, unknown> = {};
    if (node.attributes) {
      for (const [k, v] of Object.entries(node.attributes)) {
        nodeProps[k] = resolveAttr(v);
      }
    }

    const renderedChildren =
      node.children && node.children.length > 0
        ? node.children.map((child, i) => renderNode(child, i))
        : (node.content ?? undefined);

    // 5. Custom JSX Components
    const CustomComponent = components?.[node.node_type];
    if (CustomComponent) {
      return (
        <MDXErrorBoundary key={key} componentName={node.node_type}>
          <InsideJsxContext.Provider value={true}>
            <CustomComponent {...nodeProps}>{renderedChildren}</CustomComponent>
          </InsideJsxContext.Provider>
        </MDXErrorBoundary>
      );
    }

    // 6. Standard HTML Tags
    if (/^[a-z][a-z0-9]*$/.test(node.node_type)) {
      const Tag = node.node_type as keyof React.JSX.IntrinsicElements;

      // If we are inside a custom component, we render strict HTML to avoid 
      // global Markdown CSS classes from overriding component-specific layouts.
      if (insideJsx) {
        return <Tag key={key} {...(nodeProps as any)}>{renderedChildren}</Tag>;
      }

      // If outside, allow overriding standard HTML tags (e.g., mapping `h1` to a styled component)
      const StyledTag = components?.[node.node_type];
      if (StyledTag) {
        return <StyledTag key={key} {...(nodeProps as any)}>{renderedChildren}</StyledTag>;
      }
      return <Tag key={key} {...(nodeProps as any)}>{renderedChildren}</Tag>;
    }

    // 7. Fallback for Unknown Components
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[MDXRenderer] Unknown component: <${node.node_type}>`);
    }
    
    return (
      <div key={key} data-missing-component={node.node_type}>
        {renderedChildren}
      </div>
    );
  };

  /**
   * Safely maps over child nodes or returns raw content if no children exist.
   */
  const renderChildren = (node: AstNode): ReactNode => {
    if (node.children && node.children.length > 0) {
      return node.children.map((child, i) => renderNode(child, i));
    }
    return node.content ?? null;
  };

  return <>{ast.map((node, i) => renderNode(node, i))}</>;
};


export const MDXViewer = ({
  ast,
  config,
}: {
  ast: AstNode[] | null | undefined;
  config?: MDXConfig;
}) => {
  if (!ast || !Array.isArray(ast)) return null;

  return (
    <MdxConfigProvider config={config}>
      <div className="omni-mdx-root">
        <MDXContent ast={ast} />
      </div>
    </MdxConfigProvider>
  );
};