[package]
name = "core-parser"
version = "0.1.0"
edition = "2021"

[lib]
# "cdylib" est magique : ça permet de compiler en .wasm pour le web, 
# ou en .so/.dll/.dylib pour le mobile/desktop via FFI.
crate-type = ["cdylib", "rlib"]

[dependencies]
pulldown-cmark = "0.11"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.114"
